# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fconverter4

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://newregistry4.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6e0806bf8dbe4e14bb8a9a53abf63894 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_11471b96a980404f9d99a9024c78fd1e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: newregistry4.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6e0806bf8dbe4e14bb8a9a53abf63894 }}/fconverter4dd4f:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fconverter4'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_56d75f16eeb1471290c1fa8e346417f5 }}
        images: 'newregistry4.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6e0806bf8dbe4e14bb8a9a53abf63894 }}/fconverter4dd4f:${{ github.sha }}'